apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode3-frontend-deployment
  labels:
    app: episode3-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode3-frontend
  template:
    metadata:
      labels:
        app: episode3-frontend
    spec:
      containers:
      - name: episode3-frontend
        image: sheheryar1166/episode3-frontend
        ports:
        - containerPort: 3000
