apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode4-backend-deployment
  labels:
    app: episode4-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode4-backend
  template:
    metadata:
      labels:
        app: episode4-backend
    spec:
      containers:
      - name: episode4-backend
        image: sheheryar1166/episode4-backend
        ports:
        - containerPort: 5000
